### ISSUE TITLE
Flashing error

### ISSUE THREAD

**Issue by ixenion** [HELLBOY017/kernel_nothing_sm8475#5]
Sorry for new dummy issue,
But the previous was closed without any explanation, and I really want to test your kernel.

How do you flash your kernel?
What recovery do you use?

And does the kernel works on A12, A13, A14?
(A=Android)

**Comment by HELLBOY017** [comment]
Honestly I'd prefer just the compilation issues here you should be smart enough to check what devicename the any kernel script checks for. As for the Android version compatibility you should have checked the commit history. Pls stop opening useless issues if you are not going to do even the basic task of checking the repository thoroughly first.

**Comment by ixenion** [comment]
> Honestly I'd prefer just the compilation issues here you should smart enough to check what devicename the any kernel script checks for. As for the Android version compatibility you should have checked the commit history. Pls stop opening useless issues if you are not going to do even the basic task of checking the repository thoroughly first.

Yah, just think about it,
checking...

**Comment by ixenion** [comment]
Not a question, just for a history log...

So, the error "Unsupported device. Aborting..."

from here https://github.com/HELLBOY017/kernel_nothing_sm8475/issues/4 caused by the following:

Unpack last release .zip (For now it's [Meteoric-V5-Pong](https://github.com/HELLBOY017/kernel_nothing_sm8475/releases/tag/V5-Pong))
And open the file:
```
META-INF/com/google/android/update-binary
```

Here in a bash script, we can see a function where the error is happening:
```bash
do_devicecheck() {
  [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
  local device devicename match product testname vendordevice vendorproduct;
  ui_print "Checking device...";
  device=$(getprop ro.product.device 2>/dev/null);
  product=$(getprop ro.build.product 2>/dev/null);
  vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
  vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
  for testname in $(grep '^device.name.*=' anykernel.sh | cut -d= -f2-); do
    for devicename in $device $product $vendordevice $vendorproduct; do
      if [ "$devicename" == "$testname" ]; then
        ui_print "$testname" " ";
        match=1;
        break 2;
      fi;
    done;
  done;
  if [ ! "$match" ]; then
    abort " " "Unsupported device. Aborting...";
  fi;
}
```
So what the function does is gather params: device, product, vendordevice, vendorproduct and checks wheither one of them is inside anykernel.sh (from root of unzipped kernel.)
anykernel.sh contains the following device names:
```
device.name1=Pong
device.name2=PongIND
device.name3=PongEEA
```

So one of the params: device, product, vendordevice, vendorproduct should contain one of three possible variants then there would no error.
But in my case I have that error, so, lets gather these params: device, product, vendordevice, vendorproduct manually with termux:

![image](https://github.com/user-attachments/assets/966442f7-fa9d-4d61-ba33-0787ecbe9c48)

And... seems all good, there is "Pong" output for three out of four params.
I think I can just bypass this checking but it's interesting what causes the error...
Investigating further.

**Comment by HELLBOY017** [comment]
> Not a question, just for a history log...
> 
> So, the error "Unsupported device. Aborting..."
> 
> from here #4 caused by the following:
> 
> Unpack last release .zip (For now it's [Meteoric-V5-Pong](https://github.com/HELLBOY017/kernel_nothing_sm8475/releases/tag/V5-Pong)) And open the file:
> 
> ```
> META-INF/com/google/android/update-binary
> ```
> 
> Here in a bash script, we can see a function where the error is happening:
> 
> ```shell
> do_devicecheck() {
>   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
>   local device devicename match product testname vendordevice vendorproduct;
>   ui_print "Checking device...";
>   device=$(getprop ro.product.device 2>/dev/null);
>   product=$(getprop ro.build.product 2>/dev/null);
>   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
>   vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
>   for testname in $(grep '^device.name.*=' anykernel.sh | cut -d= -f2-); do
>     for devicename in $device $product $vendordevice $vendorproduct; do
>       if [ "$devicename" == "$testname" ]; then
>         ui_print "$testname" " ";
>         match=1;
>         break 2;
>       fi;
>     done;
>   done;
>   if [ ! "$match" ]; then
>     abort " " "Unsupported device. Aborting...";
>   fi;
> }
> ```
> 
> So what the function does is gather params: device, product, vendordevice, vendorproduct and checks wheither one of them is inside anykernel.sh (from root of unzipped kernel.) anykernel.sh contains the following device names:
> 
> ```
> device.name1=Pong
> device.name2=PongIND
> device.name3=PongEEA
> ```
> 
> So one of the params: device, product, vendordevice, vendorproduct should contain one of three possible variants then there would no error. But in my case I have that error, so, lets gather these params: device, product, vendordevice, vendorproduct manually with termux:
> 
> ![image](https://private-user-images.githubusercontent.com/48788888/391233929-966442f7-fa9d-4d61-ba33-0787ecbe9c48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjgzNDUsIm5iZiI6MTczMjk2ODA0NSwicGF0aCI6Ii80ODc4ODg4OC8zOTEyMzM5MjktOTY2NDQyZjctZmE5ZC00ZDYxLWJhMzMtMDc4N2VjYmU5YzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDEyMDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYzkyZGQwOTc0NGQ4NTA0MzhhMjNkZDAxNjAyYzhkOTMxODUwNjBlOGM0Y2U5OTBkOTUwZGU1YTBkNzdiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ynm_jOu0U1WkCN6EvI1TX5T4kMX2dJviqxxgeErHPGI)
> 
> And... seems all good, there is "Pong" output for three out of four params. I think I can just bypass this checking but it's interesting what causes the error... Investigating further.

Checking in stock rom is pointless as the script would check these props in recovery when you are flashing the zip from recovery

**Comment by HELLBOY017** [comment]
Anyways

> > Not a question, just for a history log...
> > So, the error "Unsupported device. Aborting..."
> > from here #4 caused by the following:
> > Unpack last release .zip (For now it's [Meteoric-V5-Pong](https://github.com/HELLBOY017/kernel_nothing_sm8475/releases/tag/V5-Pong)) And open the file:
> > ```
> > META-INF/com/google/android/update-binary
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Here in a bash script, we can see a function where the error is happening:
> > ```shell
> > do_devicecheck() {
> >   [ "$(file_getprop anykernel.sh do.devicecheck)" == 1 ] || return 1;
> >   local device devicename match product testname vendordevice vendorproduct;
> >   ui_print "Checking device...";
> >   device=$(getprop ro.product.device 2>/dev/null);
> >   product=$(getprop ro.build.product 2>/dev/null);
> >   vendordevice=$(getprop ro.product.vendor.device 2>/dev/null);
> >   vendorproduct=$(getprop ro.vendor.product.device 2>/dev/null);
> >   for testname in $(grep '^device.name.*=' anykernel.sh | cut -d= -f2-); do
> >     for devicename in $device $product $vendordevice $vendorproduct; do
> >       if [ "$devicename" == "$testname" ]; then
> >         ui_print "$testname" " ";
> >         match=1;
> >         break 2;
> >       fi;
> >     done;
> >   done;
> >   if [ ! "$match" ]; then
> >     abort " " "Unsupported device. Aborting...";
> >   fi;
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So what the function does is gather params: device, product, vendordevice, vendorproduct and checks wheither one of them is inside anykernel.sh (from root of unzipped kernel.) anykernel.sh contains the following device names:
> > ```
> > device.name1=Pong
> > device.name2=PongIND
> > device.name3=PongEEA
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So one of the params: device, product, vendordevice, vendorproduct should contain one of three possible variants then there would no error. But in my case I have that error, so, lets gather these params: device, product, vendordevice, vendorproduct manually with termux:
> > ![image](https://private-user-images.githubusercontent.com/48788888/391233929-966442f7-fa9d-4d61-ba33-0787ecbe9c48.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NjgzNDUsIm5iZiI6MTczMjk2ODA0NSwicGF0aCI6Ii80ODc4ODg4OC8zOTEyMzM5MjktOTY2NDQyZjctZmE5ZC00ZDYxLWJhMzMtMDc4N2VjYmU5YzQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDEyMDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkYzkyZGQwOTc0NGQ4NTA0MzhhMjNkZDAxNjAyYzhkOTMxODUwNjBlOGM0Y2U5OTBkOTUwZGU1YTBkNzdiN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ynm_jOu0U1WkCN6EvI1TX5T4kMX2dJviqxxgeErHPGI)
> > And... seems all good, there is "Pong" output for three out of four params. I think I can just bypass this checking but it's interesting what causes the error... Investigating further.
> 
> Checking in stock rom is pointless as the script would check these props in recovery when you are flashing the zip from recovery

Anyways use orangefox recovery to flash the kernel for now.

**Comment by ixenion** [comment]
Thanks, Il try orangefox, but first Id like to check these params values in recovery.

**Comment by ixenion** [comment]
@HELLBOY017 Bwt did you ever try to put internal wlan0 wi-fi card in monitor mode?
There is a file:
https://github.com/HELLBOY017/kernel_nothing_sm8475/blob/base/drivers/staging/qcacld-3.0/configs/default_defconfig
with line
```CONFIG_WIFI_MONITOR_SUPPORT := y```
Looks interesting :)

ALso you have a bunch of rtl drivers, does that mean the kernel supports external wi-fi cards?

**Comment by ixenion** [comment]
Iv added one line into anykernel.sh
Before:
```shell
device.name1=Pong
device.name2=PongIND
device.name3=PongEEA
```
After
```shell
device.name1=Pong
device.name2=PongIND
device.name3=PongEEA
device.name4=pong
```
Then the kernel was installed correctly:
![Screenshot_20241202-120623](https://github.com/user-attachments/assets/008a9499-6b68-49f9-9546-252a5d3babea)
